# Generated by Django 5.0.2 on 2024-04-01 01:57

import cuenta.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='usuario')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='fecha de union')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='ultimo ingreso')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, default=cuenta.models.get_default_profile_image, max_length=255, null=True, upload_to=cuenta.models.get_profile_image_filepath)),
                ('hide_email', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
